### ISSUE TITLE
Go Version Build Instructions?

### ISSUE THREAD

**Issue by haloss1** [insomniacslk/dublin-traceroute#104]
Hi, first of all, wonderful tool!, i tried installing/building the Go version for IPV6 support from these instructions, yet i'm getting the following errors:
```
dublin-traceroute/go/dublintraceroute/cmd/dublin-traceroute > go get github.com/insomniacslk/dublin-traceroute/go/dublintraceroute/cmd/dublin-traceroute
go get: module github.com/insomniacslk/dublin-traceroute@upgrade found (v0.4.2), but does not contain package github.com/insomniacslk/dublin-traceroute/go/dublintraceroute/cmd/dublin-traceroute
```

```
dublin-traceroute/go/dublintraceroute/cmd/dublin-traceroute > go get -u ./... && go build
go: cannot find main module, but found .git/config in /home/haloss1/Dev/dublin-traceroute
        to create a module there, run:
        cd ../../../.. && go mod init
```

I'm not very familiar with Go, any help is greatly appreciated, i'm doing a comparison of the routes taken from various ISPs here where i live, your tool has helped me a lot visualizing my ISPs infrastructure in IPV4, beign able to see the route in IPV6 would help me diagnose an issue i have regarding their prefix delegation method.
Thank you!

**Comment by insomniacslk** [comment]
hey @haloss1 , thanks for reporting this issue! My guess is that you are either using Go 1.16 or have Go modules enabled via GO111MODULE env var. In that case you would have to set GO111MODULE=off before building, since I haven't migrated to Go modules yet. Can you please try this and let me know? If it fails, the output of `go env` might help. Thanks!

**Comment by haloss1** [comment]
Thanks!, after setting GO111MODULE=off, i can do ```go get github.com/insomniacslk/dublin-traceroute/go/dublintraceroute/cmd/dublin-traceroute``` successfully, although i'm getting the following while using the python bindings for plotting: 
```
> python3 -m dublintraceroute plot trace.json      
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/haloss1/.virtualenvs/dublintrace/lib/python3.9/site-packages/dublintraceroute/__init__.py", line 5, in <module>
    from .dublintraceroute import (
  File "/home/haloss1/.virtualenvs/dublintrace/lib/python3.9/site-packages/dublintraceroute/dublintraceroute.py", line 7, in <module>
    from . import _dublintraceroute
ImportError: libdublintraceroute.so.0.1.1: cannot open shared object file: No such file or directory

```
```
> dublin-traceroute -v    
Dublin Traceroute v0.1
```

**Comment by insomniacslk** [comment]
The Python bindings are strictly tied to the C++ implementation. Did you install them with `make install`?

**Comment by haloss1** [comment]
Yes, thank you so much, i installed the C++ implementation from the AUR and it worked perfectly.
