### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by rosstex** [insomniacslk/dublin-traceroute#12]
Ran on the MacOS Sierra beta after compiling from source.

```
rteixeira-mbp:build rteixeira$ dublin-traceroute 8.8.8.8
Starting dublin-traceroute
Traceroute from 0.0.0.0:12345 to 8.8.8.8:33434~33443
libc++abi.dylib: terminating
Abort trap: 6
```

**Comment by rosstex** [comment]
I attempted to use brew first, but instead got
```
==> Downloading https://github.com/insomniacslk/dublin-traceroute/archive/v0.2.t
==> Downloading from https://codeload.github.com/insomniacslk/dublin-traceroute/
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ca1fdd375d2c2ce3f51f812570cbfe21e9d1244f00f07f052342031800868a6d
Actual: 5f4d9c9ee4532cb325d9c7942998f3e62b6616c6a5eb30b413b2e0633e72ee70
Archive: /Users/rteixeira/Library/Caches/Homebrew/dublin-traceroute-0.2.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by insomniacslk** [comment]
I have updated the homebrew formula to the latest, and added it to the dublin-traceroute repo, under `homebrew`, try with

```brew install https://raw.githubusercontent.com/insomniacslk/dublin-traceroute/master/homebrew/dublin-traceroute.rb```

On OSX Sierra, I don't have access to that OS version, so unfortunately I can't do much. I am happy to support if you want to debug it on your side though.

**Comment by rosstex** [comment]
Thanks, that fixed the brew issue. I can try! Been a while since I've gdb'd anything.

**Comment by insomniacslk** [comment]
Are you still having the loader issue? I can try to find a mac with that beta if so

On 13 July 2016 5:46:40 AM IST, Ross Teixeira <notifications@github.com> wrote:
>Thanks, that fixed the brew issue. I can try! Been a while since I've
>gdb'd anything.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/insomniacslk/dublin-traceroute/issues/12#issuecomment-232255461

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rosstex** [comment]
I am encountering the issue still, and haven't been able to find the bug yet.

**Comment by insomniacslk** [comment]
I am closing this bug since Sierra is in non-public beta at the moment.

@rosstex let's check this again once it's at least public beta
