### ISSUE TITLE
Build failure on Centos 7

### ISSUE THREAD

**Issue by clay584** [insomniacslk/dublin-traceroute#18]
I have built and installed the dependencies and the cmake passes all checks.  When I issue make, it fails with a lot of errors.  Any help would be greatly appiciated.

http://pastebin.com/3suXc3Vg

**Comment by insomniacslk** [comment]
Hi @clay584 , I have mixed feelings about the reason for this build failure. Among the many I believe that you should use at least gcc 4.9 to compile. Can you please try this first and let me know? Then if it doesn't work we can troubleshoot more.

**Comment by insomniacslk** [comment]
No reply in long time, closing. Feel free to reopen with more information for troubheshooting
