### ISSUE TITLE
make install failed (w/ Python 3.4)

### ISSUE THREAD

**Issue by toralf** [insomniacslk/dublin-traceroute#2]
At a hardened 64bit stable Gerntoo Linux make went fine but "sudo make install" gave ::

creating build/temp.linux-x86_64-3.4
creating build/temp.linux-x86_64-3.4/dublintraceroute
x86_64-pc-linux-gnu-g++ -pthread -fPIC -I../include -I../dependencies/libtins/include -I../dependencies/g3log/src -I../dependencies/jsoncpp/dist -I/usr/include/python3.4 -c dublintraceroute/_dublintraceroute.cc -o build/temp.linux-x86_64-3.4/dublintraceroute/_dublintraceroute.o -std=c++11 -ldublintraceroute
dublintraceroute/_dublintraceroute.cc: In function ‘PyObject* DublinTraceroute_init(PyObject*, PyObject*, PyObject*)’:
dublintraceroute/_dublintraceroute.cc:29:50: error: ‘PyString_FromString’ was not declared in this scope
  PyObject *py_sport = PyString_FromString("sport"),
                                                  ^
In file included from /usr/include/python3.4/pytime.h:6:0,
                 from /usr/include/python3.4/Python.h:65,
                 from dublintraceroute/_dublintraceroute.cc:1:
dublintraceroute/_dublintraceroute.cc:36:12: error: ‘py_dport’ was not declared in this scope
  Py_INCREF(py_dport);
            ^
/usr/include/python3.4/object.h:769:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)
                   ^
dublintraceroute/_dublintraceroute.cc:37:12: error: ‘py_target’ was not declared in this scope
  Py_INCREF(py_target);
            ^
/usr/include/python3.4/object.h:769:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)
                   ^
dublintraceroute/_dublintraceroute.cc:38:12: error: ‘py_npaths’ was not declared in this scope
  Py_INCREF(py_npaths);
            ^
/usr/include/python3.4/object.h:769:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)
                   ^
dublintraceroute/_dublintraceroute.cc:39:12: error: ‘py_max_ttl’ was not declared in this scope
  Py_INCREF(py_max_ttl);
            ^
/usr/include/python3.4/object.h:769:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)
                   ^
dublintraceroute/_dublintraceroute.cc: In function ‘PyObject* DublinTraceroute_traceroute(PyObject*, PyObject*)’:
dublintraceroute/_dublintraceroute.cc:62:71: error: ‘PyString_FromString’ was not declared in this scope
  PyObject *py_results = PyString_FromString(results->to_json().c_str());
                                                                       ^
dublintraceroute/_dublintraceroute.cc: In function ‘PyObject* init_dublintraceroute()’:
dublintraceroute/_dublintraceroute.cc:125:72: error: ‘Py_InitModule’ was not declared in this scope
     PyObject *module = Py_InitModule("_dublintraceroute", ModuleMethods);
                                                                        ^
dublintraceroute/_dublintraceroute.cc:130:67: error: ‘PyString_FromString’ was not declared in this scope
     PyObject *classNameDT = PyString_FromString("DublinTraceroute");
                                                                   ^
dublintraceroute/_dublintraceroute.cc:131:81: error: ‘PyClass_New’ was not declared in this scope
     PyObject *dublinTracerouteClass = PyClass_New(NULL, classDictDT, classNameDT);
                                                                                 ^
dublintraceroute/_dublintraceroute.cc:140:67: error: too many arguments to function ‘PyObject* PyMethod_New(PyObject*, PyObject*)’
  PyObject *method = PyMethod_New(func, NULL, dublinTracerouteClass);
                                                                   ^
In file included from /usr/include/python3.4/Python.h:93:0,
                 from dublintraceroute/_dublintraceroute.cc:1:
/usr/include/python3.4/classobject.h:23:24: note: declared here
 PyAPI_FUNC(PyObject *) PyMethod_New(PyObject *, PyObject *);
                        ^
error: command 'x86_64-pc-linux-gnu-g++' failed with exit status 1
Makefile:104: recipe for target 'python-extension' failed
make: *** [python-extension] Error 1

**Comment by insomniacslk** [comment]
Hi Toralf,

thanks for your report! The Python module has only been developed for Python 2.x so far, but the porting to 3.x should not be complicated. There are a few things that changed from 2.x to 3.x in the C API, including PyString_* that became PyBytes_* (as you see from the errors you get). I will work on it during the weekend. The documentation is at https://docs.python.org/3/howto/cporting.html if you're curious.


----- Original Message -----

**Comment by insomniacslk** [comment]
Hi Toralf,
this should be fixed in https://github.com/insomniacslk/dublin-traceroute/commit/ab2d7ccc974a606d86ab239f3eed5846ff57526d
