### ISSUE TITLE
Scaleway NAT no longer breaks traceroute

### ISSUE THREAD

**Issue by brmzkw** [insomniacslk/dublin-traceroute#28]
[In the README](https://dublin-traceroute.net/README.md) you mention Scaleway having a broken NAT. They have been upgraded, and traceroute is fine now.

```
$> mtr google.com
 Host                                                                                                                                                                           Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 10.1.8.1                                                                                                                                                                     0.0%   278    2.0   2.4   1.2  20.2   2.7
 2. ???
 3. 10.1.94.96                                                                                                                                                                   0.0%   278    1.0   1.2   0.9   1.8   0.0
 4. ???
 5. 196-225-47-212.int.cloud.online.net                                                                                                                                          0.0%   278    1.0   1.1   0.9   1.7   0.0
 6. a9k2-49-infra-dc2.dc3.poneytelecom.eu                                                                                                                                        0.0%   278    1.5   1.4   0.9   1.8   0.0
 7. 195.154.3.214                                                                                                                                                                0.0%   278    1.9   1.9   1.3  11.0   0.9
 8. 108.170.244.193                                                                                                                                                              0.0%   278    1.5   1.7   1.3   2.2   0.0
 9. 66.249.95.103                                                                                                                                                                0.0%   278    1.8   1.7   1.3   2.2   0.0
10. par21s12-in-f14.1e100.net                                                                                                                                                    0.0%   278    1.8   1.6   1.3   2.1   0.0
```

**Comment by insomniacslk** [comment]
Thanks for reporting! I will have a look at it later today and adjust the documentation as appropriate

**Comment by insomniacslk** [comment]
I've updated the README in https://github.com/insomniacslk/dublin-traceroute/pull/29 . Thanks @brmzkw for reporting this and for people at Scaleway for fixing it :)

@brmzkw out of curiosity, can you share some insight about what was the issue? A misconfiguration or some special configuration?

**Comment by insomniacslk** [comment]
Also replied on https://community.online.net/t/ping-works-but-not-traceroute/439/5

**Comment by brmzkw** [comment]
Sure,

The current NAT software that brings network to Scaleway clients is a home made software, built with [DPDK](https://dpdk.org/). The code is not opensource, but it might be in a near future.

[RFC 5508](https://tools.ietf.org/html/rfc5508) was not correctly implemented, which has been fixed recently.

Traceroute sends IP messages with short TTL and excepts to receive ICMP error messages to know which hop could not handle the packet.

An ICMP error message contains data. These data contain the IP header of the packet which originated the error. A correct NAT implementation need to rewrite not only the IP addresses contained in the outer IP packet, but also the IP addresses contained inside the ICMP data.

**Comment by insomniacslk** [comment]
Thanks for the explanation!

-- an even happier Scaleway customer (yes, dublin-traceroute.net is hosted there :) )

**Comment by insomniacslk** [comment]
also good to see that my troubleshooting on the scaleway forum was correct :) 

I'm closing this issue since it's fixed now

**Comment by halfa** [comment]
For any curious people passing by, the DPDK NAT platform [is now open-source](https://github.com/scaleway/natasha)

**Comment by insomniacslk** [comment]
> For any curious people passing by, the DPDK NAT platform [is now open-source](https://github.com/scaleway/natasha)

This is awesome! Thanks @halfa for following up and letting us know :-)
