### ISSUE TITLE
Keep DST port fixed and set a SRC base port 

### ISSUE THREAD

**Issue by h3ct0r** [insomniacslk/dublin-traceroute#31]
Hi,

I would like to know if there is the option to keep a fixed destination port and use multiple src ports? 

As I'm seeing, at the moment the source port is static, and the destination port is used as a base + the number of paths selected. Having the two options would be helpful.

**Comment by h3ct0r** [comment]
Hi @insomniacslk, I'm working on a pull request with this feature, I think it's going to be ready in a couple of days.

**Comment by insomniacslk** [comment]
Fixed in https://github.com/insomniacslk/dublin-traceroute/pull/34
