### ISSUE TITLE
Inter-packet delay

### ISSUE THREAD

**Issue by h3ct0r** [insomniacslk/dublin-traceroute#33]
Hi,

Not exactly an issue but more like a documentation explanation:
What does the inter-packet delay in milliseconds do and how it affects the trace? For example: What could be a reasonable expectation of changing this number to 100 milliseconds or 1 millisecond?

Thanks!

**Comment by insomniacslk** [comment]
hey @h3ct0r :) the inter-packet delay is the time (in ms) that the packet processor waits before sending the next packet.

For example, in a traceroute with 2 paths and TTL from 1 to 5, dublin-traceroute would send:
* all the packets on the first path, from TTL 1 to TTL 10
* all the packets on the second path, from TTL 1 to TTL 10

What happens with the inter-packet delay is:
* packet for path 1 and TTL 1 is sent
* wait NN milliseconds (the inter-packet delay)
* packet for path 1 and TTL 2 is sent
* wait NN milliseconds
* and so on

The code that sleeps for the inter-packet delay is at https://github.com/insomniacslk/dublin-traceroute/blob/master/src/dublin_traceroute.cc#L228 .

Let me know if you need further clarification

**Comment by h3ct0r** [comment]
Hi @insomniacslk , your explanation is very clear! No need for further clarifications! :)
Thanks!
