### ISSUE TITLE
https://dublin-traceroute.net/repo gives a 404 error

### ISSUE THREAD

**Issue by q2dg** [insomniacslk/dublin-traceroute#70]
So installation instructions for CentOS packages fail.
Thanks!

**Comment by insomniacslk** [comment]
Hello @q2dg , apologies, I missed the notification for this! The CentOS installation information is outdated, you should use the `teknoraver/networking` COPR, see https://copr.fedorainfracloud.org/coprs/teknoraver/networking/package/dublin-traceroute/ . I will update the installation instructions in the documentation

**Comment by insomniacslk** [comment]
Updated in https://github.com/insomniacslk/dublin-traceroute/pull/72

**Comment by insomniacslk** [comment]
this is resolved
