### ISSUE TITLE
...tracebox?

### ISSUE THREAD

**Issue by alicektx** [insomniacslk/dublin-traceroute#71]
Hi! Not an 'issue' at all by any means actually -
was just curious if you were aware of tracebox?
[http://www.tracebox.org/](http://www.tracebox.org/)

dublin-traceroute.net explains very well in simple terms for us non-gurus,
the differences between dublin-traceroute & paris-traceroute.
So i'd really love to further hear (& learn from) your thoughts in regards to tracebox at some point...

All the best

**Comment by insomniacslk** [comment]
Hello @alicektx ! I am aware of tracebox, I'll try to explain what I think are the main differences between tracebox and dublin-traceroute:

* the main one: tracebox aims at detecting packet manipulation, while dublin-traceroute aims at giving a view as complete as possible of a multipath network
* tracebox works with TCP, while dublin-traceroute currently only focuses on UDP (TCP probes are on the roadmap but unfortunately I don't have much time for a side project at the moment)
* tracebox, if I recall correctly, does a regular traceroute, not a multipath traceroute. This means that it probes a much smaller number of paths, and will probably have an incorrect and/or incomplete view of the topology. While topology correctness is not an issue for tracebox's goals (but it is for dublin-traceroute), the incomplete view means that it may not detect all of the middleboxes on the path between A and B
* the NAT detection algorithm of dublin-traceroute should be more robust than tracebox's one (happy to be disproved of course!), as I'm using the IP ID field (with IP fragmentation disabled, so it's normally ignored by routers and middleboxes), to keep track of the packet. This is one of the two packet identification methods

Things you can do with tracebox but not with dublin-traceroute:
* detect manipulations of the TCP header
* run scripts
(possibly something else, but I'm not familiar with the tracebox codebase)

Things you can do with dublin-traceroute but not with tracebox:
* rebuild an accurate topology in case of multipath networks
* generate JSON output to feed into data analysis tools (e.g. jq, pandas, see the [README of python-dublin-traceroute](https://github.com/insomniacslk/python-dublin-traceroute/blob/master/README.md))
* provide a graphical representation


I hope this is useful, feel free to ask me any question.

**Comment by alicektx** [comment]
Deeply thank you for your time & detailed explanations!!

Was reading about zstd, then started browsing facebook's other github repos,
stumbled upon fbtracert, which got me extremely curious & interested,
so from there on eventually one thing brought the next one etc etc...

Some truly awesome research & algorithms you guys are developing...:fire: 
Kinda getting older here (and gone are the days that ping, 
traceroute & a simple tcp syn scanner got the 'basic diagnosis' done),
hence at moments i'm having this fear (hopefully irrational!),
of waking up one morning, and not being able 
(being the average(?) end-user / small networks admin i've always been),
to understand at least the basics of how things '_currently work_', 
not being able to catch up...

Once again, extremely grateful for your time - highly appreciated. :star:
All the best!
