### ISSUE TITLE
How to use TCP & ICMP protocal instaed of UDP protocol (Default) while doing tracing 

### ISSUE THREAD

**Issue by anburhce** [insomniacslk/dublin-traceroute#73]
Hi Andrea,

I have used Centos repo to install dublin-traceroute and the version details u can find below.

Installed version v0.4.2

![image](https://user-images.githubusercontent.com/23453745/73956502-0b495c80-492b-11ea-8e51-e7b9a576c647.png)

How do I select or use TCP/ICMP instead of UDP protocol? I do not find any option in v0.4.2 in help output.

Kindly assist.

**Comment by insomniacslk** [comment]
Hi @anburhce, TCP and ICMP probes are not implemented. The code has been refactored to simplify the addition of new probe types, but so far I didn't have a chance to work on it. If you want of course feel free to submit a PR!

**Comment by anburhce** [comment]
Fixes #73
