### ISSUE TITLE
Allow overriding trace.json output with a different name

### ISSUE THREAD

**Issue by omribahumi** [insomniacslk/dublin-traceroute#80]
Would also be cool to write the JSON output to stdout directly.
Other stuff can go to stderr.

Maybe specifiable with a flag?

**Comment by insomniacslk** [comment]
you can already use -o/--output-file` for that, I guess you would rather change the default from trace.json to stdout?

**Comment by insomniacslk** [comment]
Changing the default is OK for me, it's the same thing I already do in the Go implementation. I'll put up a PR
