### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by NavinF** [insomniacslk/dublin-traceroute#9]
FYI: https://dublin-traceroute.net/ returns `502 Bad Gateway`.

**Comment by insomniacslk** [comment]
Thanks for the report @NavinF , it's back up now.

Also, good to see that there is interest around Dublin Traceroute. I'd love to hear how people use it!

**Comment by NavinF** [comment]
Wow that was fast! :)

**Comment by NavinF** [comment]
Wow that was fast! :) 

There is indeed interest in Dublin Traceroute. I might send a few PRs once I figure out how to to make it stop using the wrong source IP.

**Comment by insomniacslk** [comment]
Nice to hear that!

On the PR, if you have a specific request or just want to discuss on something that would be interesting to fix/add, feel free to open an issue
